In [46]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

df=pd.read_csv(r"C:\Users\harshit\Downloads\REGRESSION\encoding\country data.csv")
df

country  age  salary
0   france   44   72000
1    spain   27   48000
2  germany   30   54000
3    spain   38   61000
4  germany   40   68000
5   france   35   58000
6    spain   32   55000
7   france   48   79000
8  germany   50   83000
9   france   37   67000

In [47]:
x=df[['country','age']]

In [48]:
y=df['salary']

In [56]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features=[0])
x=ohe.fit_transform(x).toarray()
x

array([[ 1.,  0.,  0., 44.],
       [ 0.,  0.,  1., 27.],
       [ 0.,  1.,  0., 30.],
       [ 0.,  0.,  1., 38.],
       [ 0.,  1.,  0., 40.],
       [ 1.,  0.,  0., 35.],
       [ 0.,  0.,  1., 32.],
       [ 1.,  0.,  0., 48.],
       [ 0.,  1.,  0., 50.],
       [ 1.,  0.,  0., 37.]])

In [57]:
X=x[:,1:]
X

array([[ 0.,  0., 44.],
       [ 0.,  1., 27.],
       [ 1.,  0., 30.],
       [ 0.,  1., 38.],
       [ 1.,  0., 40.],
       [ 0.,  0., 35.],
       [ 0.,  1., 32.],
       [ 0.,  0., 48.],
       [ 1.,  0., 50.],
       [ 0.,  0., 37.]])

In [58]:
W=LinearRegression()
W.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [59]:
W.predict([[0,0,44]])

array([73162.76978417])

In [51]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df.country=le.fit_transform(df.country)
df

country  age  salary
0        0   44   72000
1        2   27   48000
2        1   30   54000
3        2   38   61000
4        1   40   68000
5        0   35   58000
6        2   32   55000
7        0   48   79000
8        1   50   83000
9        0   37   67000

In [52]:
x=df[['country','age']]
y=df['salary']

In [53]:
from sklearn.linear_model import LinearRegression
A=LinearRegression()
A.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [54]:
A.predict([[2,55]])

array([87482.92611127])

In [55]:
A.predict([[0,44]])

array([73722.36532234])