In [59]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [27]:
df = pd.read_csv("D:\DATA SCIENCE\data set/homeprice.csv") 

In [28]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [29]:
#handle missing value:
df.bedroom.median()

3.5

In [30]:
#i want the integer value:
import math
median_bedroom = math.floor(df.bedroom.median())
median_bedroom

3

In [31]:
df.bedroom = df.bedroom.fillna(median_bedroom)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

data is prepare now train model to find out price of home that has:

3000 sqr ft area, 3 bedroom, 40 year old

2500 sqr ft area, 4 bedroom, 5 year old

In [32]:
#linear regression class object:
reg = linear_model.LinearRegression()
# I will call fit method to train model using indepntdent and dependent varible
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [33]:
reg.coef_ # the value of m1, m2, m3

array([   137.25, -26025.  ,  -6825.  ])

In [34]:
reg.intercept_ #value of b

383724.9999999998

equation will be:

price(dependent) = m1*area(independent) +m2*bedroom(independent) + m3*age(independent) + b 

where m1,m2,m3 are coefficients

In [38]:
#predict price for 3000 sqr ft area, 3 bedroom, 40 year old

reg.predict([[3000,3,40]]) 

array([444400.])

In [43]:
# need to check how it is calculated using equation
137.25*3000+-26025*3+-6825*40+383724.9999999998

444399.9999999998

In [44]:
#also predict 2500 sqr ft area, 4 bedroom, 5 year old
reg.predict([[2500,4,5]])

array([588625.])

# Exercise

using hiring csv need to build ML model for HR department to predect salries for:

2 yr exp, 9 test score, 6 interview score

12 yr exp, 10 test score, 10 interview score

In [64]:
hr_df = pd.read_csv("D:\DATA SCIENCE\data set/hiring.csv")
hr_df

exp  test_score  interview_score  salary
0   NaN         8.0                9   50000
1   NaN         8.0                6   45000
2   5.0         6.0                7   60000
3   2.0        10.0               10   65000
4   7.0         9.0                6   70000
5   3.0         7.0               10   62000
6  10.0         NaN                7   72000
7  11.0         7.0                8   80000

In [65]:
from pytz import all_timezones
print (all_timezones)

['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Asmera', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Timbuktu', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'Ameri